[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DIMSAI_TEENSY_SCAFFOLD=1
  -DIMSAI_BOOT_MODE=IMSAI_BOOT_MONITOR_THEN_DISK
  -DUSB_SERIAL
  -DEXCLUDE_Z80
  -I./src
  -I./z80core
  -I./iodevices

build_src_filter = +<*>
