#ifndef IMSAI_BOOT_MODE_H
#define IMSAI_BOOT_MODE_H

#define IMSAI_BOOT_MONITOR_ONLY 0
#define IMSAI_BOOT_MONITOR_THEN_DISK 1
#define IMSAI_BOOT_AUTOBOOT_IMDOS 2

#ifndef IMSAI_BOOT_MODE
#define IMSAI_BOOT_MODE IMSAI_BOOT_MONITOR_THEN_DISK
#endif

#endif